version: 2.0
jobs:
  build:
    environment:
      IMAGE_NAME: earendil06/oh-my-system
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Login to dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Deploy the docker image
          command: docker push $IMAGE_NAME:latest
  test:
    docker:
      - image: earendil06/oh-my-system
        environment:
          ANSIBLE_PATH: toto
    steps:
      - checkout
      - run: ls
      - run: echo $PWD
      - run:
          name: Install additional plugins & dependencies
          command: install-galaxy
      - run:
          name: Run the playbook
          command: run-playbook


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
