version: 2.0
jobs:
  build:
    working_directory: /temp
    docker:
      - image: alpine/git
    steps:
      - checkout
      - attach_workspace:
          at: /temp
      - persist_to_workspace:
          root: /temp
          paths:
            - ./ansible
            - ./scripts
  test:
    working_directory: /temp
    docker:
      - image: earendil06/kazaar-configuration
    steps:
      - attach_workspace:
          at: /temp
      - run:
          name: "Copy of the sources"
          command: mv ./ansible/* /ansible
      - run:
          name: "Install additional plugins & dependencies"
          command: ./scripts/install-galaxy.sh
      - run:
          name: "Run the playbook"
          command: ./scripts/run-playbook.sh


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
