#!/usr/bin/env bash

ansible-playbook $ANSIBLE_PATH/playbooks/playbook.yml \
--extra-vars "@$ANSIBLE_PATH/config/globals.json" \
--extra-vars "@$ANSIBLE_PATH/config/customs.json" \
--extra-vars "hosts" -i $ANSIBLE_PATH/config/hosts
